### PR TITLE
Add nystudio107/craft-seomatic - 2020-04-28-1

### PR DESCRIPTION
**Pull request by brandonkelly**

### CODE REVIEW

**Comment by brandonkelly** [comment]
@fabpot The validator is saying `Invalid branch name "v3".`, but that’s the actual branch name (https://github.com/nystudio107/craft-seomatic/tree/v3) so not sure what to do about that.

**Comment by fabpot** [comment]
Should be 3.x IIRC (in my phone right now)

**Comment by fabpot** [comment]
Should be 3.x IIRC (in my phone right now)

**Comment by brandonkelly** [comment]
Thanks, that’s passing locally. Not sure I understand why `3.x` is acceptable but not `v3`, when `v3` is the actual Git branch name. Would be good if the docs could clarify that a bit more.

**Pull request merged**
