### PR TITLE
add CVE against reveal.js

### PR DESCRIPTION
**Pull request by drsassafras**

### CODE REVIEW

**Comment by fabpot** [comment]
This repo is about PHP security issues, looks like a JS lib here with no Packagist entry.

**Comment by drsassafras** [comment]
Did I not get the packagist entry correct? https://packagist.org/packages/components/revealjs

**Comment by drsassafras** [comment]
Or perhaps you are saying that because it is a JS dependency listed on packagist that it is excluded from security advisories here?

**Comment by garas** [comment]
JS packages should be primarily installed with npm/bower/yarn. Composer should be used for PHP libraries.

https://github.com/components has many Composer wrappers for various JS packages and many of them has one or more CVE. Do you want duplicate them all here?

**Pull request closed without merging**
