### PR TITLE
Adding Flow-SA-2015-001 and Neos-SA-2015-002

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by stof** [comment]
shouldn't we have 2 advisories, one for the arbitrary file upload and another one for the XEE ?

**Comment by kdambekalns** [comment]
We have released one Flow advisory, and fixed both issues in the same release. To me it seems the entries here should be consistent with the advisories… No?

**Comment by stof** [comment]
but the affected versions are not the same for both issues

**Comment by kdambekalns** [comment]
Still seemed to make sense to have a "combined advisory" from our POV. But you have a point there, and with the next advisory (hopefully will take a while!) we'll keep that in mind.

As of today, as I see it, this database reflects the advisories released, not the other way around… So I'd be happy if this could be merged, unless the API and/or CLI checker have an issue with the current PR. But looking at the data, it should detect that there is an issue for the affected versions and point to the advisory. So it should be fine, no?

**Comment by stof** [comment]
@kdambekalns this was mostly a suggestion. It is not preventing the merge IMO (but I'm not a merger here)

**Comment by kdambekalns** [comment]
Ok, I see. Anyway, thanks!

**Pull request merged**
