### PR TITLE
SS 2015 009

### PR DESCRIPTION
**Pull request by spekulatius**

### CODE REVIEW

**Comment by Ocramius** [comment]
@spekulatius is there a reason why you are creating a single PR for each advisory? I'm basically just archiving gmail inbox messages from you...

**Comment by spekulatius** [comment]
@Ocramius its an habit from internal peer reviewing. Sorry, I can just open one.

**Comment by Ocramius** [comment]
@spekulatius that would be better, as otherwise you're sending notifications to > 70 people for no good reason.

Thanks for your understanding :-)

**Comment by spekulatius** [comment]
No problem. That makes a lot of sense. I'll open one final one and that's it for now.

**Comment by spekulatius** [comment]
Hello @Ocramius ,

I opened the final PR. This will be the last mail for now. Thanks for you patience with me.

spek

**Pull request merged**
