### PR TITLE
Add Drupal SA-CORE-2020-013

### PR DESCRIPTION
**Pull request by ericbarrette**

### CODE REVIEW

**Comment by stof** [comment]
these 2 CVEs are actually not about the drupal package, but about `pear/archive_tar`, which is a dependency of drupal. So that's the package to which the advisory needs to be attached (which also benefits other packages using it)

**Comment by ericbarrette** [comment]
Good catch, I'm assuming they will be raised in Drupal projects if we do so?

**Comment by stof** [comment]
given that `drupal/core` and `drupal/drupal` depend on `pear/archive_tar` rather than bundling it, yes, because your composer.lock file contains `pear/archive_tar`

**Comment by stof** [comment]
And this was already added in https://github.com/FriendsOfPHP/security-advisories/pull/507 btw

**Comment by ericbarrette** [comment]
Ok thank you, I'm closing this PR.

**Pull request closed without merging**
