### PR TITLE
Allow time to be null when the issue is not fixed yet

### PR DESCRIPTION
**Pull request by fabpot**
Alternative to #242. I don't think we need the `unfixed` entry. Having a `time` set as `null` is semantically enough.

/cc @paragonie-scott @stof

### CODE REVIEW

**Comment by stof** [comment]
Not making any change to the validator looks weird to me. Does it work ?

And for unfixed vulnerabilities, we also need to be able to mark all versions as impacted (so no upper bound)

**Comment by fabpot** [comment]
The validator does not care about the value of the `time` entry, it just validates that it's present.

For the upper bound, it's just a matter of using a very high version, I don't think we need anything special here. As done in #241 (even if I would use a version a bit higher than `9`, let's say `999`).

**Comment by fabpot** [comment]
I think trying to keep the current semantic as much as possible is important here.

**Comment by stof** [comment]
but setting to `null` will not be considered as there when checking with `isset`

**Comment by fabpot** [comment]
@stof indeed, fixed

**Pull request merged**
