### PR TITLE
Correcting YAML syntax for branch names

### PR DESCRIPTION
**Pull request by Ocramius**
Also, this is reason 8400347509437 for YAML being a shitty configuration format.

Fitting quote:

 > The story so far:
 > In the beginning the Universe was created.
 > This has made a lot of people very angry and been widely regarded as a bad move.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by stof** [comment]
this looks like something which should be added to the validator script to be automated, no ?

**Comment by Ocramius** [comment]
@stof not sure if it can be automated, as it fails in the Yaml component itself. Maybe an addition to the YAML stuff?

**Comment by stof** [comment]
@Ocramius A solution could be to enforce branches not to have numeric names in the validator (the branch is generally set as ``1.x`` or ``2.4.x`` for versionned branches). This would solve it as this would parse as a Yaml string.

What we could do in the Yaml component to avoid loosing float keys is to cast them to string before adding them to the array instead of letting PHP cast it (which will cast to int)

**Comment by Ocramius** [comment]
> What we could do in the Yaml component to avoid loosing float keys

The actual bug, I suppose. Can you report it, if you got time? Currently being kicked out...

**Comment by Ocramius** [comment]
Reported in symfony/symfony#15667

**Pull request merged**
