### PR TITLE
Make broken yaml files valid

### PR DESCRIPTION
**Pull request by reiz**
I used http://www.yamllint.com to check if the yaml files are valid. This pull request includes little improvements to keep the files valid.

### CODE REVIEW

**Comment by reiz** [comment]
**Don't accept this pull request yet!** More files are affected and I have to do a couple more commits.

**Comment by reiz** [comment]
Now the pull request is ready to merge :-) 27 files are affected.

**Comment by GrahamCampbell** [comment]
Wow. This will need squashing to one commit. ;)

**Comment by xabbuh** [comment]
:+1: (@fabpot can squash the commits when merging by the way)

**Comment by fabpot** [comment]
Thank you @reiz.

**Pull request closed without merging**
