### PR TITLE
Silverstripe advisories July 2024

### PR DESCRIPTION
**Pull request by emteknetnz**

### CODE REVIEW

**Review by xabbuh — CHANGES_REQUESTED** [review]
Can you fix the CI issues please by renaming the two mentioned files?

**Comment by emteknetnz** [comment]
Sorry about that. Fixed now.

**Comment by xabbuh** [comment]
Silverstripe versions before 5.0 are not affected?

**Comment by xabbuh** [comment]
https://github.com/advisories/GHSA-chx7-9x8h-r5mg and https://packagist.org/packages/silverstripe/framework/advisories?version=7025938 claim older versions to be affected too if I don't miss anything

**Comment by emteknetnz** [comment]
Good spot, have fixed.

**Review by xabbuh — APPROVED** [review]

**Pull request merged**
