### PR TITLE
simplesamlphp SSPSA 201612-01: Incorrect signature validation

### PR DESCRIPTION
**Pull request by jdreesen**
This has already beed added for `simplesamlphp/saml2` in #182 but SimpleSAMLphp itself is also affected.

### CODE REVIEW

**Comment by marcomenzel** [comment]
I'm not sure about these kind of issues. I had a look into SimpleSAMLphp, in my opinion it is only effected because of the dependency to the saml2-package?!

**Comment by fabpot** [comment]
If the security issue only comes from a dependency managed by Composer, the advisory should be removed. @marcomenzel Can you confirm?

**Comment by marcomenzel** [comment]
I do. I'm really sure about that. 
Commit 27b7efb81ad8d0fecbba725c0004aacedcaae1c8 in simplesamlphp solves the issue/pr in  https://github.com/simplesamlphp/saml2/pull/81 

It seems like the simplesamlphp team is used to do it this way (patch version bump on dependency security issues). Propably to get some attention from simplesamlphp-endusers.

**Comment by fabpot** [comment]
reverted, thanks @marcomenzel

**Comment by jdreesen** [comment]
Oh, well. Sorry for the mistake :(

**Comment by Ocramius** [comment]
@jdreesen mistakes happen - no need to be sorry :-)

**Pull request merged**
