### PR TITLE
added laravel/framework entry

### PR DESCRIPTION
**Pull request by yeroon**
Fixes a vulnerability in the QueryBuilder due to unexpected bindings.

### CODE REVIEW

**Comment by yeroon** [comment]
@fabpot thanks for quickly merging 👍

**Comment by jaylinski** [comment]
@yeroon Can you also add an entry for `illuminate/database`? 🙏

**Comment by pieterw2w** [comment]
Is it possible to have a better URL for this one? The URL provided for information contains no information what the security leak is and how it can be misused. I can not find a CVE for it either.

**Comment by xabbuh** [comment]
@pieterw2w Looks like #529 tries to address this.

**Pull request merged**
